name: ecommerce2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_text_form_field: ^1.0.5
  google_fonts: ^6.2.0
  http: ^1.2.0
  image: ^4.2.0
  image_picker: ^1.0.8
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
